// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: data/v1/anime.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Known anime types.
public enum Data_V1_AnimeType: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case unknown // = 0
  case tv // = 1
  case ova // = 2
  case ona // = 3
  case movie // = 4
  case special // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .tv
    case 2: self = .ova
    case 3: self = .ona
    case 4: self = .movie
    case 5: self = .special
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .tv: return 1
    case .ova: return 2
    case .ona: return 3
    case .movie: return 4
    case .special: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Data_V1_AnimeType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Data_V1_AnimeType] = [
    .unknown,
    .tv,
    .ova,
    .ona,
    .movie,
    .special,
  ]
}

#endif  // swift(>=4.2)

/// Airing status of a single anime show.
public enum Data_V1_AiringStatus: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case unknown // = 0
  case unaired // = 1
  case airing // = 2
  case aired // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .unaired
    case 2: self = .airing
    case 3: self = .aired
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .unaired: return 1
    case .airing: return 2
    case .aired: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Data_V1_AiringStatus: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Data_V1_AiringStatus] = [
    .unknown,
    .unaired,
    .airing,
    .aired,
  ]
}

#endif  // swift(>=4.2)

/// Name of the season when an anime show started airing.
public enum Data_V1_AiringSeason: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case unknown // = 0
  case summer // = 1
  case fall // = 2
  case winter // = 3
  case spring // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .summer
    case 2: self = .fall
    case 3: self = .winter
    case 4: self = .spring
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .summer: return 1
    case .fall: return 2
    case .winter: return 3
    case .spring: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Data_V1_AiringSeason: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Data_V1_AiringSeason] = [
    .unknown,
    .summer,
    .fall,
    .winter,
    .spring,
  ]
}

#endif  // swift(>=4.2)

/// Represents anime genre.
///
/// Default locale is en-US.
public struct Data_V1_AnimeGenre {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Genre identifier.
  public var id: UInt64 = 0

  /// Genre name.
  public var name: String = String()

  /// Genre summary.
  public var summary: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Represents a single anime show.
public struct Data_V1_Anime {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Show's identifier.
  public var id: UInt64 = 0

  /// Name of the show in romanji.
  public var name: String = String()

  /// URL of the poster thumbnail.
  public var thumbnailURL: String = String()

  /// Type of the show.
  public var type: Data_V1_AnimeType = .unknown

  /// Airing season.
  public var season: Data_V1_AiringSeason = .unknown

  /// Airing season year,
  public var year: Int32 = 0

  /// Airing status.
  public var airingStatus: Data_V1_AiringStatus = .unknown

  /// Score from 0 to 10.
  public var score: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "data.v1"

extension Data_V1_AnimeType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "ANIME_TYPE_UNKNOWN"),
    1: .same(proto: "ANIME_TYPE_TV"),
    2: .same(proto: "ANIME_TYPE_OVA"),
    3: .same(proto: "ANIME_TYPE_ONA"),
    4: .same(proto: "ANIME_TYPE_MOVIE"),
    5: .same(proto: "ANIME_TYPE_SPECIAL"),
  ]
}

extension Data_V1_AiringStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "AIRING_STATUS_UNKNOWN"),
    1: .same(proto: "AIRING_STATUS_UNAIRED"),
    2: .same(proto: "AIRING_STATUS_AIRING"),
    3: .same(proto: "AIRING_STATUS_AIRED"),
  ]
}

extension Data_V1_AiringSeason: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "AIRING_SEASON_UNKNOWN"),
    1: .same(proto: "AIRING_SEASON_SUMMER"),
    2: .same(proto: "AIRING_SEASON_FALL"),
    3: .same(proto: "AIRING_SEASON_WINTER"),
    4: .same(proto: "AIRING_SEASON_SPRING"),
  ]
}

extension Data_V1_AnimeGenre: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AnimeGenre"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "name"),
    3: .same(proto: "summary"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularUInt64Field(value: &self.id)
      case 2: try decoder.decodeSingularStringField(value: &self.name)
      case 3: try decoder.decodeSingularStringField(value: &self.summary)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularUInt64Field(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.summary.isEmpty {
      try visitor.visitSingularStringField(value: self.summary, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_V1_AnimeGenre, rhs: Data_V1_AnimeGenre) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.summary != rhs.summary {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Data_V1_Anime: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Anime"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "name"),
    3: .standard(proto: "thumbnail_url"),
    4: .same(proto: "type"),
    5: .same(proto: "season"),
    6: .same(proto: "year"),
    7: .standard(proto: "airing_status"),
    8: .same(proto: "score"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularUInt64Field(value: &self.id)
      case 2: try decoder.decodeSingularStringField(value: &self.name)
      case 3: try decoder.decodeSingularStringField(value: &self.thumbnailURL)
      case 4: try decoder.decodeSingularEnumField(value: &self.type)
      case 5: try decoder.decodeSingularEnumField(value: &self.season)
      case 6: try decoder.decodeSingularSInt32Field(value: &self.year)
      case 7: try decoder.decodeSingularEnumField(value: &self.airingStatus)
      case 8: try decoder.decodeSingularFloatField(value: &self.score)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularUInt64Field(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.thumbnailURL.isEmpty {
      try visitor.visitSingularStringField(value: self.thumbnailURL, fieldNumber: 3)
    }
    if self.type != .unknown {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 4)
    }
    if self.season != .unknown {
      try visitor.visitSingularEnumField(value: self.season, fieldNumber: 5)
    }
    if self.year != 0 {
      try visitor.visitSingularSInt32Field(value: self.year, fieldNumber: 6)
    }
    if self.airingStatus != .unknown {
      try visitor.visitSingularEnumField(value: self.airingStatus, fieldNumber: 7)
    }
    if self.score != 0 {
      try visitor.visitSingularFloatField(value: self.score, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_V1_Anime, rhs: Data_V1_Anime) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.thumbnailURL != rhs.thumbnailURL {return false}
    if lhs.type != rhs.type {return false}
    if lhs.season != rhs.season {return false}
    if lhs.year != rhs.year {return false}
    if lhs.airingStatus != rhs.airingStatus {return false}
    if lhs.score != rhs.score {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
