//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: rpc/v1/news.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate Rpc_V1_NewsServiceClient, then call methods of this protocol to make API calls.
public protocol Rpc_V1_NewsServiceClientProtocol {
  func latestNews(_ request: Rpc_V1_LatestNewsRequest, callOptions: CallOptions?) -> UnaryCall<Rpc_V1_LatestNewsRequest, Rpc_V1_LatestNewsResponse>
}

public final class Rpc_V1_NewsServiceClient: GRPCClient, Rpc_V1_NewsServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the rpc.v1.NewsService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }

  /// Fetches and returns a list of latest anime news.
  ///
  /// - Parameters:
  ///   - request: Request to send to LatestNews.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func latestNews(_ request: Rpc_V1_LatestNewsRequest, callOptions: CallOptions? = nil) -> UnaryCall<Rpc_V1_LatestNewsRequest, Rpc_V1_LatestNewsResponse> {
    return self.makeUnaryCall(path: "/rpc.v1.NewsService/LatestNews",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

}


// Provides conformance to `GRPCPayload` for request and response messages
extension Rpc_V1_LatestNewsRequest: GRPCProtobufPayload {}
extension Rpc_V1_LatestNewsResponse: GRPCProtobufPayload {}

