// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: data/v1/trailer.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Represents a single anime trailer.
public struct Data_V1_Trailer {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The anime the trailer is related to.
  public var anime: Data_V1_Anime {
    get {return _anime ?? Data_V1_Anime()}
    set {_anime = newValue}
  }
  /// Returns true if `anime` has been explicitly set.
  public var hasAnime: Bool {return self._anime != nil}
  /// Clears the value of `anime`. Subsequent reads from it will return its default value.
  public mutating func clearAnime() {self._anime = nil}

  /// URL of the video stream.
  public var videoURL: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _anime: Data_V1_Anime? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "data.v1"

extension Data_V1_Trailer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Trailer"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "anime"),
    2: .standard(proto: "video_url"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._anime)
      case 2: try decoder.decodeSingularStringField(value: &self.videoURL)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._anime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.videoURL.isEmpty {
      try visitor.visitSingularStringField(value: self.videoURL, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_V1_Trailer, rhs: Data_V1_Trailer) -> Bool {
    if lhs._anime != rhs._anime {return false}
    if lhs.videoURL != rhs.videoURL {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
